config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments
  resources :pictures, only: [:index,:show]
  resources :articles , only: [:index,:show]do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
      get :add_view_count
    end
  end
  resources :vendors do
    collection do
      post :upload_image
      get :show_gps
      get :add_comments
      get :top_search
      get :details
      get :review
      get :add_review
    end
  end

  namespace :admin do
    root to: 'employees#desboart'
    resources :categories do
      collection do
        get :show_name
      end  
    end
    resources :comments do
      collection do
        get :show_name
      end  
    end  

    resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
        get  :add_employees
        post :save_employees
      end  
    end 

    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end

    resources :articles do
      collection do
        post :upload_image
      end
    end

    resources :pictures do
      collection do
        post :upload_image
        get :show_gps
      end
    end

    resources :users do
      collection do
        post :create_import_users
        get :import_users
      end
    end

    resources :vendors do
      collection do
        post :upload_image
        get :show_gps
      end
    end 

  end

  namespace :web do
    resources :center do
      collection do
        get :my_vendor
        get :my_visit
        get :my_search
        get :visits_converse_create 
      end
    end
  end

  #root to: '/admin/employees'
  #root to: 'admin/employees#index'
  root to: 'vendors#review'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  devise_for :users, path: "web", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "web/sessions", passwords: "web/passwords"}

end

app/models/permission.rb
class Permission < ApplicationRecord

end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @q = SearchParams.new(params[:search_params] || {})
    @permissions = Permission.default_where(@q.attributes(self)).page(params[:page]).per(10)
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end
 def show_name
    @permission = permission.find(params[:id])
    render json: {name: @permission.name}
  end
  # GET /permissions/new
  def new
    @permission = permission.new
  end
  def add_roles
    @permission = Permission.find(params[:id])
  end

  def save_roles
    @permission = Permission.find(params[:id])
    @permission.role_ids = params[:permission][:role_ids]
  end
  
  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = permission.new(permission_params)
    @permission.save
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    @permission.update(permission_params)
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to "index", notice: 'permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:parent_id,:name)
    end
end

app/views/admin/permissions/_add_roles.html.erb
<%= simple_form_for @permission, url: save_roles_admin_permissions_path(id:@permission.id) , method: :post, remote: true, html: {id:"add_roles"} do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <% Role.all.each do |role|%>
	    <label class="checkbox">
	      <%= check_box_tag "permission[role_ids][]",role.id,@permission.role_ids.include?(role.id )%> <%= role.name %>
	    </label>
	<% end %>
	<br/>
    
    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/permissions/_list.html.erb
<tr id="permis_<%= permission.id %>">
  <td class="center aligned">
    <span><%= permission.id%></span>
  </td>
  <td class="center aligned">
    <%=  permission.name%>
  </td>
  <td class="center aligned">
    <%= permission.action_tag %>
  </td>
  <td class="center aligned">
    <%= permission.controller_tag %>
  </td>
  <td class="center aligned">
    <%= link_to add_roles_admin_permissions_path(id:permission.id),remote: true, data: {content: '分配角色', variation: 'inverted'}, class: 'ui green icon button' do %>
      <i class="edit icon"></i>
    <% end %>
  </td>
</tr>

app/views/admin/permissions/add_roles.js.erb
$('#addrole_modal').remove();
$('body').append('<div class="ui modal" id="addrole_modal"><i class="close icon"></i><h2 class="ui dividing header">分配角色</h2><%= j(render 'add_roles') %></div>');
$('#addrole_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

$("#commition").click(function(){
    $("#add_roles").submit(); 
});

app/views/admin/permissions/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>权限管理</h2>
  </div>
</div>
<div class="ui blue segment">
	<div class="ui grid">
    <div class="left floated wide column">
      <%= link_to '新增分类', new_admin_category_path, class: 'ui primary button', remote: true  %>
    </div>
  </div>  
  <table class="ui selectable striped celled table">
    <thead>
    <tr >
      <th class="center aligned">name</th>
      <th class="center aligned">action_tag</th>
      <th class="center aligned">controller_tag</th>
    </tr>
    </thead>
    <tbody>
    <%= render :partial => "list", :collection => @permissions, :as => :permission %>
    </tbody>
  </table>
  <span class="blue">
    <%= page_entries_info(@permissions) %>
  </span>
  <%= paginate(@permissions, :theme => 'admin')%>
</div>

app/views/admin/permissions/save_roles.js.erb
 $("#addrole_modal").modal('hide');