config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments
  resources :pictures, only: [:index,:show]
  resources :articles , only: [:index,:show]do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
      get :add_view_count
    end
  end
  resources :vendors do
    collection do
      post :upload_image
      get :show_gps
      get :add_comments
      get :top_search
      get :details
      get :review
      get :add_review
    end
  end

  namespace :admin do
    root to: 'employees#desboart'
    resources :categories do
      collection do
        get :show_name
      end  
    end
    resources :comments do
      collection do
        get :show_name
      end  
    end  

    resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
        get  :add_employees
        post :save_employees
      end  
    end 

    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end

    resources :articles do
      collection do
        post :upload_image
      end
    end

    resources :pictures do
      collection do
        post :upload_image
        get :show_gps
      end
    end

    resources :users do
      collection do
        post :create_import_users
        get :import_users
      end
    end

    resources :vendors do
      collection do
        post :upload_image
        get :show_gps
      end
    end 

  end

  namespace :web do
    resources :center do
      collection do
        get :my_vendor
        get :my_visit
        get :my_search
        get :visits_converse_create 
      end
    end
  end

  #root to: '/admin/employees'
  #root to: 'admin/employees#index'
  root to: 'vendors#review'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  devise_for :users, path: "web", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "web/sessions", passwords: "web/passwords"}

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :attachments, as: :attachment_entity
  belongs_to :category, optional: true
  belongs_to :user
  belongs_to :vendor
  has_many :comments
  serialize :tag

	def user_name
    "@#{self.user&.name}"
	end

	def self.view_count_top
    order(view_count: :desc).limit(10)
	end

	def cover_img_path
    return self.cover_img if self.activity_id == 1
  	self.cover_img ? Attachment.find(self.cover_img.to_i).path.url : "/assets/f10.jpg"
  end

  def mpt
    self.mp3 ? Attachment.find(self.mp3).path.url : ""
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:title]
      @articles = Article.where("title like ? ","%#{params[:title]}%").order(id: :desc).page(params[:page]).per(10)
    elsif params[:category_id]
      @articles = Article.where(category_id:params[:category_id]).order(id: :desc).page(params[:page]).per(10)
    else
      @articles = Article.all.order(id: :desc).page(params[:page]).per(10)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        unless params[:draft_img].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:draft_img], created_by: 1 ) 
          @article.cover_img = attachment.id
          @article.save
        end
        unless params[:mp3].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:mp3], created_by: 1 ) 
          @article.mp3 = attachment.id
          @article.save
        end
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        unless params[:draft_img].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:draft_img], created_by: 1 ) 
          @article.cover_img = attachment.id
          @article.save
        end
        unless params[:mp3].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:mp3], created_by: 1 ) 
          @article.mp3 = attachment.id
          @article.save
        end
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_image
    attachment = Attachment.create(attachment_entity_type: "Article", path: params[:wang_editor_file], created_by: 1 )
    render plain: attachment.path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:category_id,:title,:content,:cover_img,:mp3,:min_show,:user_id,:vendor_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy,:add_comments,:add_view_count]
  layout "article"

  # GET /articles
  # GET /articles.json
  def index
    if params[:title]
      @articles = Article.where("title like ? ","%#{params[:title]}%").page(params[:page]).per(10)
    elsif params[:category_id]
      @articles = Article.where(category_id:params[:category_id]).page(params[:page]).per(10)
    else
      @articles = Article.all.page(params[:page]).per(10)
    end
  end

  def top_search
    @articles = Article.joins(:user).where("title like :q or articles.item_no = '#{params[:title]}' or users.name like :q ",{q: "#{params[:title]}%"} ).page(params[:page]).per(10)
    render "index"
  end

  def add_comments
    Comment.create(article_id:@article.id,content:params[:comment_text])
    render :partial => 'add_comments'
  end

  # 点赞计数
  def add_view_count
    @article.update(view_count:(@article.view_count + params[:view_count].to_i))
    render json: { view_count: @article.view_count } 
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article.update(view_count: @article.view_count.to_i + 1)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        unless params[:draft_img].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:draft_img], created_by: 1 ) 
          @article.cover_img = attachment.id
          @article.save
        end
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        unless params[:draft_img].blank?
          attachment = Attachment.create(attachment_entity_type: "Article",attachment_entity_id: @article.id , path: params[:draft_img], created_by: 1 ) 
          @article.cover_img = attachment.id
          @article.save
        end
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_image
    attachment = Attachment.create(attachment_entity_type: "Article", path: params[:wang_editor_file], created_by: 1 )
    render plain: attachment.path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find_by(id:params[:id]) || Article.find_by(id:1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:category_id,:title,:content,:cover_img,:min_show,:user_id,:vendor_id)
    end
end

app/views/admin/articles/_form.html.erb
<br/><br/>
<%= form_for @article, url: url, method: meth, :html => { :multipart => true } do |f| %>

  <div class="field">
    封面图片：<%= file_field_tag "draft_img", id: 'draft_img' %>
  </div>

  <div class="field">
    背景音乐：<%= file_field_tag "mp3", id: 'mp3' %>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :category, 'Category', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.select :category_id, options_for_select(Category.where(mode:"Article").collect { |p| [ p.name, p.id ] }, ''), {include_blank: "选择类型"}, {class: 'form-control input-sm  ui dropdown', style: 'width: 280px;' } %>
	  </div>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :user_id, 'User', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.select :user_id, options_for_select(User.all.collect { |p| [ p.name, p.id ] }, ''), {include_blank: "选择用户"}, {class: 'form-control input-sm  ui dropdown', style: 'width: 280px;' } %>
	  </div>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :vendor_id, '商家', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.select :vendor_id, options_for_select(Vendor.all.collect { |p| [ p.name, p.id ] }, ''), {include_blank: "选择商家"}, {class: 'form-control input-sm  ui dropdown', style: 'width: 280px;' } %>
	  </div>
  </div>

  <div class="control-group optional form-group field ui form" style="margin-top: 10px" >
	  <%= f.label :title, 'Title', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.text_field :title, class: 'form-control input-sm', style: 'width: 280px;' %>
	  </div>
  </div>

  <div class="control-group optional form-group field ui form" style="margin-top: 10px" >
	  <%= f.label :min_show, 'Show-title', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= f.text_field :min_show, class: 'form-control input-sm', style: 'width: 280px;' %>
	  </div>
  </div>

  <div class="control-group optional form-group field" style="margin-top: 10px" >
	  <%= f.label :content, 'Content', class: 'password optional control-label' %>
	  <div class="controls">
	    <%= text_area_tag 'article[content]', @article.content, { rows: 100, class: 'form-control input-sm'  } %>
	  </div>
  </div>
  
 <div class="row-fluid">
	<a href="javascript:history.back();"><div class="ui button cancel">返回</div></a>
    <%= f.submit :class=>"ui primary button"%>
  </div>
<% end %>


<% content_for :scripts do %>
	<%= javascript_include_tag 'wangEditor.min' %>
    <%= stylesheet_link_tag    'wangEditor.min' %>
	<script>
		//富文本编辑器初始化
		var editor = new wangEditor('article_content');
		//图片上传配置
		editor.config.uploadImgUrl = "/admin/articles/upload_image";
		editor.config.uploadImgFileName = "wang_editor_file"
		editor.config.uploadHeaders = {
		'Accept' : 'text/x-json',
		'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
		};
		editor.create();
		editor.$editorContainer.css('z-index', 0);
	</script>
<% end %>

app/views/admin/articles/_list.html.erb
<tr id="article_<%= article.id %>">
  <td class="center aligned">
    <span><%= article.id%></span>
  </td>
  <td class="center aligned">
    <%= article.title%> 
  </td>
  <td class="center aligned">
    <%= article.user_name %>
  </td>
  <td class="center aligned">
    <%= link_to edit_admin_article_path(article), data: {content: '修改', variation: 'inverted'}, class: 'ui blue icon button' do %>
      <i class="edit icon"></i>
    <% end %>
  </td>
</tr>

app/views/admin/articles/edit.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>编辑文章</h2>
  </div>
</div>
<%= render 'form', url: admin_article_path(@article), meth: :put %>

app/views/admin/articles/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>文章管理</h2>
  </div>
</div>
<%#= render 'search_form'  %>
<div class="ui blue segment">
  <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to new_admin_article_path, class: 'ui primary button' do %>
        <i class="plus icon"></i>新增文章
      <% end %>
    </div>
  </div>
  <table class="ui selectable striped celled table">
    <thead>
    <tr >
      <th class="center aligned">ID</th>
      <th class="center aligned">标题</th>
      <th class="center aligned">作者</th>
      <th class="center aligned">操作</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'list', collection: @articles, as: :article %>
    </tbody>
  </table>
  <span class="blue">
    <%= page_entries_info(@articles) %>
  </span>
  <%= paginate(@articles, :theme => 'admin')%>
</div>

app/views/admin/articles/new.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>新建文章</h2>
  </div>
</div>
<%= render 'form', url: admin_articles_path, meth: :post %>

app/views/admin/articles/show.html.erb
<div class="ui blue segment">
	<h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a><%= @article.title %></h2>
	<% if @article.mpt.present? %>
	  <audio autoplay="autoplay" controls="controls"loop="loop" preload="auto"
	              src="<%= @article.mpt %>">
	        你的浏览器不支持audio标签
	  </audio>
	<% end %>
	<br/><br/>
	<%= @article.content.html_safe %>
</div>